#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yamato Osada
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
cnt = 0
for line in sys.stdin:
    try:
        ans += int(line)
        cnt += 1
    except:
        ans += float(line)
        cnt += 1
ans = ans/cnt
print(ans)
