#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yamato Osada
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 1
for line in sys.stdin:
    try:
        ans *= int(line)
    except:
        ans *= float(line)

print(ans)
