#!/usr/bin/python3
#SPDX-FileCopyrighttText: 2023 Yamato Osada
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
